---
- name: Install direnv package
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name: direnv
    state: present

- name: Install direnv hook
  ansible.builtin.lineinfile:
    state: present
    dest: ~/.bashrc
    line: 'eval "$(direnv hook bash)"'
